// google web interface languages
// https://sites.google.com/site/tomihasa/google-language-codes
VALID_LANGUAGES = {
  'af': {'name': 'Afrikaans'},
  'ak': {'name': 'Akan'},
  'sq': {'name': 'Albanian'},
  'am': {'name': 'Amharic'},
  'ar': {'name': 'Arabic'},
  'hy': {'name': 'Armenian'},
  'az': {'name': 'Azerbaijani'},
  'eu': {'name': 'Basque'},
  'be': {'name': 'Belarusian'},
  'bem': {'name': 'Bemba'},
  'bn': {'name': 'Bengali'},
  'bh': {'name': 'Bihari'},
  'xx-bork': {'name': 'Bork, bork, bork!'},
  'bs': {'name': 'Bosnian'},
  'br': {'name': 'Breton'},
  'bg': {'name': 'Bulgarian'},
  'km': {'name': 'Cambodian'},
  'ca': {'name': 'Catalan'},
  'chr': {'name': 'Cherokee'},
  'ny': {'name': 'Chichewa'},
  'zh-CN': {'name': 'Chinese (Simplified)'},
  'zh-TW': {'name': 'Chinese (Traditional)'},
  'co': {'name': 'Corsican'},
  'hr': {'name': 'Croatian'},
  'cs': {'name': 'Czech'},
  'da': {'name': 'Danish'},
  'nl': {'name': 'Dutch'},
  'xx-elmer': {'name': 'Elmer Fudd'},
  'en': {'name': 'English'},
  'eo': {'name': 'Esperanto'},
  'et': {'name': 'Estonian'},
  'ee': {'name': 'Ewe'},
  'fo': {'name': 'Faroese'},
  'tl': {'name': 'Filipino'},
  'fi': {'name': 'Finnish'},
  'fr': {'name': 'French'},
  'fy': {'name': 'Frisian'},
  'gaa': {'name': 'Ga'},
  'gl': {'name': 'Galician'},
  'ka': {'name': 'Georgian'},
  'de': {'name': 'German'},
  'el': {'name': 'Greek'},
  'gn': {'name': 'Guarani'},
  'gu': {'name': 'Gujarati'},
  'xx-hacker': {'name': 'Hacker'},
  'ht': {'name': 'Haitian Creole'},
  'ha': {'name': 'Hausa'},
  'haw': {'name': 'Hawaiian'},
  'iw': {'name': 'Hebrew'},
  'hi': {'name': 'Hindi'},
  'hu': {'name': 'Hungarian'},
  'is': {'name': 'Icelandic'},
  'ig': {'name': 'Igbo'},
  'id': {'name': 'Indonesian'},
  'ia': {'name': 'Interlingua'},
  'ga': {'name': 'Irish'},
  'it': {'name': 'Italian'},
  'ja': {'name': 'Japanese'},
  'jw': {'name': 'Javanese'},
  'kn': {'name': 'Kannada'},
  'kk': {'name': 'Kazakh'},
  'rw': {'name': 'Kinyarwanda'},
  'rn': {'name': 'Kirundi'},
  'xx-klingon': {'name': 'Klingon'},
  'kg': {'name': 'Kongo'},
  'ko': {'name': 'Korean'},
  'kri': {'name': 'Krio (Sierra Leone)'},
  'ku': {'name': 'Kurdish'},
  'ckb': {'name': 'Kurdish (Soranî)'},
  'ky': {'name': 'Kyrgyz'},
  'lo': {'name': 'Laothian'},
  'la': {'name': 'Latin'},
  'lv': {'name': 'Latvian'},
  'ln': {'name': 'Lingala'},
  'lt': {'name': 'Lithuanian'},
  'loz': {'name': 'Lozi'},
  'lg': {'name': 'Luganda'},
  'ach': {'name': 'Luo'},
  'mk': {'name': 'Macedonian'},
  'mg': {'name': 'Malagasy'},
  'ms': {'name': 'Malay'},
  'ml': {'name': 'Malayalam'},
  'mt': {'name': 'Maltese'},
  'mi': {'name': 'Maori'},
  'mr': {'name': 'Marathi'},
  'mfe': {'name': 'Mauritian Creole'},
  'mo': {'name': 'Moldavian'},
  'mn': {'name': 'Mongolian'},
  'sr-ME': {'name': 'Montenegrin'},
  'ne': {'name': 'Nepali'},
  'pcm': {'name': 'Nigerian Pidgin'},
  'nso': {'name': 'Northern Sotho'},
  'no': {'name': 'Norwegian'},
  'nn': {'name': 'Norwegian (Nynorsk)'},
  'oc': {'name': 'Occitan'},
  'or': {'name': 'Oriya'},
  'om': {'name': 'Oromo'},
  'ps': {'name': 'Pashto'},
  'fa': {'name': 'Persian'},
  'xx-pirate': {'name': 'Pirate'},
  'pl': {'name': 'Polish'},
  'pt-BR': {'name': 'Portuguese (Brazil)'},
  'pt-PT': {'name': 'Portuguese (Portugal)'},
  'pa': {'name': 'Punjabi'},
  'qu': {'name': 'Quechua'},
  'ro': {'name': 'Romanian'},
  'rm': {'name': 'Romansh'},
  'nyn': {'name': 'Runyakitara'},
  'ru': {'name': 'Russian'},
  'gd': {'name': 'Scots Gaelic'},
  'sr': {'name': 'Serbian'},
  'sh': {'name': 'Serbo-Croatian'},
  'st': {'name': 'Sesotho'},
  'tn': {'name': 'Setswana'},
  'crs': {'name': 'Seychellois Creole'},
  'sn': {'name': 'Shona'},
  'sd': {'name': 'Sindhi'},
  'si': {'name': 'Sinhalese'},
  'sk': {'name': 'Slovak'},
  'sl': {'name': 'Slovenian'},
  'so': {'name': 'Somali'},
  'es': {'name': 'Spanish'},
  'es-419': {'name': 'Spanish (Latin American)'},
  'su': {'name': 'Sundanese'},
  'sw': {'name': 'Swahili'},
  'sv': {'name': 'Swedish'},
  'tg': {'name': 'Tajik'},
  'ta': {'name': 'Tamil'},
  'tt': {'name': 'Tatar'},
  'te': {'name': 'Telugu'},
  'th': {'name': 'Thai'},
  'ti': {'name': 'Tigrinya'},
  'to': {'name': 'Tonga'},
  'lua': {'name': 'Tshiluba'},
  'tum': {'name': 'Tumbuka'},
  'tr': {'name': 'Turkish'},
  'tk': {'name': 'Turkmen'},
  'tw': {'name': 'Twi'},
  'ug': {'name': 'Uighur'},
  'uk': {'name': 'Ukrainian'},
  'ur': {'name': 'Urdu'},
  'uz': {'name': 'Uzbek'},
  'vi': {'name': 'Vietnamese'},
  'cy': {'name': 'Welsh'},
  'wo': {'name': 'Wolof'},
  'xh': {'name': 'Xhosa'},
  'yi': {'name': 'Yiddish'},
  'yo': {'name': 'Yoruba'},
  'zu': {'name': 'Zulu'},
}
